apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- argocd-install.yaml
# Commented out until cert-manager is installed
# - certificate.yaml
- istio-gateway.yaml
- istio-virtualservice.yaml
