apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: rennovate
data:
  config.json: |-
    {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "autodiscoverFilter": ["jay123q/minisform-kuber-cluster", "jay123q/minecraft-cluster-gitops"],
      "automerge": true
      "extends": ["schedule:automergeDaily", ":dependencyDashboard"]
    }

    # "dryRun": "full",
    # "automerge": true
