apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: rennovate
spec:
  # schedule: '*/10 * * * *' 
  schedule: '0 0 * * 0' # run at 12 on sunday
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: RENOVATE_TOKEN
                - name: RENOVATE_GIT_AUTHOR
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: RENOVATE_GIT_AUTHOR
                - name: RENOVATE_AUTODISCOVER
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: RENOVATE_AUTODISCOVER
                - name: RENOVATE_PLATFORM
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: RENOVATE_PLATFORM
                - name: RENOVATE_CONFIG_FILE
                  value: /config/config.json
                - name: LOG_LEVEL
                  value: debug
              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
