apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: rennovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:L51AfXlZI85Z0up31COfCf+NOEfuDLwLeIZOhIPc6h4BGUucltG1sG+YMI8G/HVkbDDlUJQLzqXG6m9ca2PU+bTEcflh2oOZIC2bfPLU3pPpiGIzFg1exI31NsXc,iv:XtXtOHyhu0ZWD3w9YrzGWOpnpJ80tFfzhVJAD9qP6Xc=,tag:YObcvng7facgLsFXAfsi6w==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:0v7ag7j44RFaU8Vu04JqtIAzJBEW1j2MPt5W+ShD3TiTPA==,iv:OUFxZMWg67qJfIKnIoFsiInMrD54qDtyWT+oQi+QLRw=,tag:iEMIiC8i1nxvpqsDgu/W9Q==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:MRqtxQ==,iv:c2iv1MeM9FsbyXTQw3bMSVq1k8YnDCfNtMuJvCX1jKI=,tag:FG382hQ+wqahOs8HltoFag==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:tz7SsF9Y,iv:AamBoq/N9oIZGItn5vk19oXqxymUapNt64tWjL28iwI=,tag:fz2nC9bhCLbXWZQEq+7+JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zj4wa4h4z44jh0ftwahr7h3dghkw34caqenvteesvvh32cwv9dxs0aq7hp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRFE4QnNFdlo5SFBVKzhC
            a3VEMjJ0V2Q4ZDBKQmQxUUNhWXpDbEFYKzBFCnNHZTc3bkVXbGsyUUxYSW9JdDl3
            aW1ZcUNkanhOU1duMTR6L1NXT1h4eFEKLS0tIHd6OU5xL1lSd2FRY1NMNG1GVTV0
            SlJnamtwdUY0RHVqa24rWDlzQWpLS3MKn/VKvC2mEzy30BlWvry4SVYzkw5QhEz9
            IC5psjQRgAz97eGMz4LHWjLAXPcakJowwJo9p82SNjxBxF3h043jsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T20:32:49Z"
    mac: ENC[AES256_GCM,data:r/o2vusLP7uK36lUGAxCNgaPbNJCsurDLPAcLQMP8coPE9+st4an5ummBoLrTIaW+U3f+YcrU8awqUuytSfSWLrH4QRI6nuGVhixhPNRE8Fa5GdAxmDmqDovmZsFSEpMB9SHnC+SOULSQPGfSFY0i3cpFOAWzPfYsBAxvNCnAJ0=,iv:sKfFVewhu0lpuiD1YbRvSCpJEWAGXnfZ1bf8RKWiCbA=,tag:uiD7F3BC5Fx5e8dEHqXvlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
