apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: rennovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:f2Q+KVC+wNQrMYLh83XaX+I3IMXz7UzGTx/w/fKos/07ufIx7KKRn2vYDtKXQR1DQhLyJeMxbUq7yGpb1MbsdCkKObXYMSaaMWRWosHo99oMpwvpllFIMToHgu6F,iv:i6YPYBI8nDSJ3KOiZxsXp6QAF+DtDDdqic5V0exZjZ4=,tag:NBS/Z/DCE4Y7g9RezvKNTw==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:0v7ag7j44RFaU8Vu04JqtIAzJBEW1j2MPt5W+ShD3TiTPA==,iv:OUFxZMWg67qJfIKnIoFsiInMrD54qDtyWT+oQi+QLRw=,tag:iEMIiC8i1nxvpqsDgu/W9Q==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:MRqtxQ==,iv:c2iv1MeM9FsbyXTQw3bMSVq1k8YnDCfNtMuJvCX1jKI=,tag:FG382hQ+wqahOs8HltoFag==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:tz7SsF9Y,iv:AamBoq/N9oIZGItn5vk19oXqxymUapNt64tWjL28iwI=,tag:fz2nC9bhCLbXWZQEq+7+JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zj4wa4h4z44jh0ftwahr7h3dghkw34caqenvteesvvh32cwv9dxs0aq7hp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRFE4QnNFdlo5SFBVKzhC
            a3VEMjJ0V2Q4ZDBKQmQxUUNhWXpDbEFYKzBFCnNHZTc3bkVXbGsyUUxYSW9JdDl3
            aW1ZcUNkanhOU1duMTR6L1NXT1h4eFEKLS0tIHd6OU5xL1lSd2FRY1NMNG1GVTV0
            SlJnamtwdUY0RHVqa24rWDlzQWpLS3MKn/VKvC2mEzy30BlWvry4SVYzkw5QhEz9
            IC5psjQRgAz97eGMz4LHWjLAXPcakJowwJo9p82SNjxBxF3h043jsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T01:54:01Z"
    mac: ENC[AES256_GCM,data:RlIk8suh4q5oudZbh4d116+XFgjM+8RxUrsOtqID/vkTMZ2OyN+3WoGLOTSnRuCw5F5O3K6lyzH7I3n4ucp5iUVhaY5B44bduJYxl/g5L9y8TsYzdd9qzu3IsCCnVWdPhDiSgNrRCo7hA0oXg166rjIb0sDZSSclCeRnPi8aRJI=,iv:mj7TWR/PQf2u+jf56bwJ+Y8Tz6t2jGvfuYZD5lX+DnE=,tag:KNB2kcVrn9gPGCJ9MRmbaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
