---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minecraft-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/jay123q/minecraft-cluster-gitops.git
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-cluster
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: minecraft-cluster-gitops
  # path: ./../../../../minecraft-cluster-gitops/cluster
  path: ./cluster
  prune: true
  wait: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: minecraft-server
    namespace: minecraft
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-cor-cluster
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: minecraft-cluster-gitops
  # path: ./../../../../minecraft-cluster-gitops/minecraft-cor-server/cluster
  path: ./minecraft-cor-server/cluster
  prune: true
  wait: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: minecraft-cor-server
    namespace: minecraft-cor