apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- argocd-production.yaml
- argocd-staging.yaml
- cilium-helmrepo.yaml
- cilium-helmrelease.yaml
