apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/my-cluster/infrastructure/metallb
  prune: true
  wait: false
  dependsOn:
    - name: cilium
